### ISSUE TITLE
Doesn't work with base16-tomorrow

### ISSUE THREAD

**Issue by paradox460** [xcezzz/semanticolor#1]
Not sure if this is actually a bug, and if it isn't I apologise, but it appears the auto-generation of colors isn't working with the base16-tomorrow theme that ships with atom. The colors are much brighter than any other colors in the theme, and as such, make it difficult to use

**Comment by xcezzz** [comment]
Is it possible to provide a screenshot? I switched to it. I am not sure if I have a different screen brightness/gamma/contrast, or if that makes a difference. It is not *that* bad, but knowing what you are seeing will ensure if I am on the same page.

**Comment by xcezzz** [comment]
In an effort to give you more control over the colors generated. You should now have 4 additional settings that supply the %s supplied to the color generating LESS function.

I also tried to make these default values work a bit better on light themes so you wont have to muck with them. The new settings you can play with and see how they will affect the colors. See README for the function used if you are familiar with LESS and want to see how it is done.

**Comment by paradox460** [comment]
That did the trick, thank you. It was just taking the colors and oversaturating them to the point at which they didn't fit into the theme anymore.

I was able to tweak it down to a usable state.

An interesting suggestion I thought of: since atom supports all sorts of css stuff, you might consider having this plugin apply, say, different backgrounds to variables, as opposed to changing their text color.

Thanks!
