### ISSUE TITLE
Language specific settings do not persist across updates

### ISSUE THREAD

**Issue by 34code** [xcezzz/semanticolor#11]
I see this extension is updating a lot.. 

Every time it updates, I lose my language specific settings (such as "mute comments") and have to redo them. Is there a way that I can persist these changes across versions?

**Comment by sharedprophet** [comment]
I'll look into doing a better job of preserving settings.

**Comment by 34code** [comment]
@sharedprophet thanks so much!

**Comment by sharedprophet** [comment]
Please get 3.4.0 and let me know if you lose any settings. I tried to make it less likely to clobber them. Thanks.

**Comment by 34code** [comment]
Thanks -- I'll try and let you know @sharedprophet !

**Comment by sharedprophet** [comment]
I don't think this is an issue anymore. Closing.
