### ISSUE TITLE
ES6 template literals - interpolation colouring

### ISSUE THREAD

**Issue by davidsharp** [xcezzz/semanticolor#12]
I'm really liking Semanticolor, however my main issue with it is that it's not very useful when it comes to template literal colouring.

By default, the template literal uses the my theme's styling, which marks what's in the `${}` of a template literal, however, I lose out on the colourisation of those same variables that I'm using elsewhere. Alternatively, I can restore that functionality by colourising strings, but that just runs them into a jumble of colours, which is no good for a plethora of other reasons.

Support for the colourisation of variables within template literal interpolation blocks would be extremely useful.

**Theme colouring**
![screen shot 2016-10-20 at 10 16 30](https://cloud.githubusercontent.com/assets/5731838/19554028/9fd0f62a-96ae-11e6-8bf4-4b4296e1eff3.png)

**Colourisation colouring**
![screen shot 2016-10-20 at 10 18 40](https://cloud.githubusercontent.com/assets/5731838/19554029/9fd2f272-96ae-11e6-91e7-85acd8992e29.png)

**Comment by sharedprophet** [comment]
Thanks. I'll look into this soon.

**Comment by sharedprophet** [comment]
What JavaScript grammar are you using?

**Comment by davidsharp** [comment]
I'm using the ES6 Babel grammar.

**Comment by davidsharp** [comment]
It's gandm's `language-babel` specifically.

**Comment by sharedprophet** [comment]
Fixed in 3.4.0.
