### ISSUE TITLE
Possible to add setting for coloring based on theme colors?

### ISSUE THREAD

**Issue by Sawtaytoes** [xcezzz/semanticolor#13]
Since semantic colors look the same in various color schemes, I was wondering if it would be better to take color cues from the color scheme itself and color based on those instead of a rainbow.

What I'm proposing is taking advantage of points of color from the color scheme and using that to create a "theme" of colors to change tint which should ultimately allow them to better fit with the color scheme but still look like unique vars.

As far as I've seen, having the same colors for vars no matter the language and color scheme is a great idea and very beneficial, but the impact is everything looks samey and this is unchangeable without disabling semantic colors.

**Comment by sharedprophet** [comment]
I wanted to do this but it isn't practical. There is no easy way to read the color settings from the theme.
