### ISSUE TITLE
Semanticolor sometimes isn't applied when re-opening atom

### ISSUE THREAD

**Issue by penntaylor** [xcezzz/semanticolor#14]
Description of issue:
I have several files open in atom, all using semanticolor-Ruby as the grammar. I close atom. When I later restart atom, my files load up as expected...but sometimes they have semanticolor-Ruby as the grammar and other times they have plain Ruby as the grammar. I would expect them to open up with semanticolor-Ruby. If I then open up a Ruby file from the tree browser, it will have semanticolor-Ruby applied automatically (as expected), regardless of what grammar was applied to the files auto-opened at startup.

The behavior isn't specific to Ruby grammar; it happens with all other languages I use regularly.

Atom version is 1.12.6 (current release), but have seen this issue on a few different previous atom versions.

Is there some setting I've overlooked that would force the semanticolor grammar variant when restarting atom?

**Comment by sharedprophet** [comment]
I think this has to do with the order in which packages are loaded. There is code in semanticolor to try to fix it, but I haven't figured out how to do it reliably yet. If it doesn't colorize the editor windows that are open, you can disable and re-enable semanticolor to colorize them without closing and reopening the tabs.

**Comment by Sawtaytoes** [comment]
That's the workaround I'm doing as well. What about the order? Can I manually fix it?

**Comment by sharedprophet** [comment]
No, it doesn't seem to be deterministic and I don't think there's anything you can do manually. But I can probably fix it by just putting in a timeout on activation. I'll try that soon.

**Comment by Sawtaytoes** [comment]
Thanks! I can add, it always loads on my desktop, but never loads on my tablet.

I'm assuming it just takes too long to start up :/ on slower systems.

**Comment by sharedprophet** [comment]
I'm seeing the issue with 3.4.2, haha. Will work on a better fix soon.

**Comment by sharedprophet** [comment]
Should be fixed with 3.4.4.

**Comment by paradoxxxzero** [comment]
Still having the issue with 3.4.4 and 3.4.5

**Comment by sharedprophet** [comment]
When it occurs, if you open the dev tools are there any semanticolor-related error messages?

**Comment by paradoxxxzero** [comment]
Sadly no. I'll try to investigate a bit more.
Anyway thanks for this awesome package!

**Comment by paradoxxxzero** [comment]
I think I found a solution #16 for this race condition. I don't know if it would impact startup time though.

**Comment by booch** [comment]
I've been seeing Semanticolor say it has to reload every window after starting up Atom. I looked in the console and saw errors suggesting that I run `apm rebuild`. I did that in `~/.atom/.apm` and it seems to have fixed the problem.
