### ISSUE TITLE
Need documentation of settings

### ISSUE THREAD

**Issue by booch** [xcezzz/semanticolor#18]
I'm trying to tweak my Semanticolor settings. In particular, I'm wanting keys in YAML colorized, but not values. It's not clear how the settings (*Primitives*, *Keywords*, *Language Elements*, etc.) map to those in YAML. A pointer to where to find that would be appreciated.

Even looking at the source for `language-yaml`, I still don't see anything that maps to those names. I see that the left-hand side is a `entity.name.tag.yaml`, but not idea where to find how that maps.

I realize that this question will be mostly answered by resources external to Semanticolor. I'm just asking that some pointers be added to the documentation, so that using Semanticolor will be easier.

**Comment by sharedprophet** [comment]
Place the cursor on a key and open the command palette (by default shift+ctrl+P on Windows/Linux, shift+cmd+P on Mac). Use the "Log Cursor Scopes" command to show what the scopes are at that cursor position. You can use that info to figure out how to set the settings like you want them.

**Comment by sharedprophet** [comment]
Please get 3.5.0. There are now explanations of what scopes are meant for each setting.
