### ISSUE TITLE
Cannot find module sugar

### ISSUE THREAD

**Issue by BudiKusasi** [xcezzz/semanticolor#19]
Atom version 1.14.4 x64 on Windows 8
semanticolor ver. 3.4.8
this package do not function at atom start and let atom reports:
Cannot find module 'sugar'

**Comment by sharedprophet** [comment]
Did you install through Atom or by cloning the repo? If you pulled from GitHub, you have to do an `npm install` (or `yarn`) in the project folder.

**Comment by sharedprophet** [comment]
Closing, as this doesn't seem to be a `semanticolor` issue.  Please re-open if the above does not work.
