### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by j-walker23** [xcezzz/semanticolor#2]
Hello, this was auto created from Atom. Which is an awesome freaking feature lol.

Anyway, i am in the process of setting up Atom for the first time and have packages everywhere so i am sure this is just me being a noob.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [semanticolor](https://github.com/xcezzz/semanticolor) package, v0.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /Users/john/.dotfiles/atom.symlink/packages/semanticolor/lib/semanticolor.js:328

TypeError: Cannot read property 'mainModule' of undefined
    at /Users/john/.dotfiles/atom.symlink/packages/semanticolor/lib/semanticolor.js:328:57
    at complete (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7697:25)
    at delayed (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:7707:11)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".bundle",
      ".git",
      "log",
      "repositories",
      "tmp",
      "vendor"
    ],
    "hideGitIgnoredFiles": true,
    "disabledPackages": [
      "background-tips",
      "exception-reporting",
      "metrics",
      "linter-9e-sass",
      "neon-cursor",
      "neon-cursor",
      "neon-selection",
      "atom-prettify",
      "atom-jshint",
      "color-picker",
      "docblockr",
      "emmet",
      "find-selection",
      "fixmyjs",
      "jsformat",
      "last-cursor-position",
      "linter-coffeelint",
      "linter-eslint",
      "linter-jshint",
      "linter-tslint",
      "minimap",
      "pretty-json",
      "language-javascript-semantic",
      "task-list"
    ],
    "projectHome": "/Users/john/git",
    "themes": [
      "one-dark-ui",
      "monokai-seti"
    ],
    "destroyEmptyPanes": false
  },
  "semanticolor": {
    "affectedSourceObjects": {}
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
angularjs-styleguide-snippets, v0.7.2
atom-justify, v0.4.1
atom-typescript, v5.2.3
auto-update-packages, v1.0.0
color-tabs, v0.1.8
color-tabs-regex, v0.2.1
compass, v0.9.1
file-icons, v1.6.2
git-diff-details, v0.19.0
git-go, v1.0.1
git-log, v0.4.1
javascript-snippets, v1.0.0
language-javascript-better, v1.5.0
linter, v1.2.4
monokai-seti, v0.7.0
pain-split, v1.4.0
project-manager, v1.15.11
semanticolor, v0.2.2
terminal-status, v1.6.8
the-closer, v0.5.0
tool-bar-main, v0.0.8
trailing-spaces, v0.3.2
tree-view-git-branch, v0.0.2
tree-view-git-status, v0.1.2
vim-mode, v0.57.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by xcezzz** [comment]
This is odd. You should not be getting this if the package is activated.

I see you have quite a large amount of disabled packages. 
Are you having issues with any other packages when they are enabled?

Have you tried restarting Atom? 

Open up the dev tool console (CMD+OPTION+i). Select 'console' at the top.

Paste this into the console and hit enter

```
atom.packages.getActivePackage('semanticolor')
```

It should return something that should have an arrow next to the result.
Click the 'arrow' to expand it, and then just copy and paste the result.
Otherwise let me know if it just returns something like 'undefined'.

**Comment by j-walker23** [comment]
I was having lots of problems. 
I have not gotten back to using atom to much, but i did just install this package again and everything seems fine.

If i see something again i'll open a new issue. Thank you
