### ISSUE TITLE
Opt-in instead of opt-out

### ISSUE THREAD

**Issue by pferreir** [xcezzz/semanticolor#20]
One of the things that currently bothers me in semanticolor is the fact that it is enabled by default in all my languages. That basically breaks the highlighting in e.g. templating languages where semantic coloring only makes things harder to understand.
Would it be possible to disable the module by default for every language, and have the user enable it on a one-by-one basis? Or at least have a whitelist of languages where the module is known to work fine.

Otherwise, thanks for this great module!

**Comment by sharedprophet** [comment]
There is a blacklist for languages that are known to not work (currently not configurable, though). What grammars don't work? I can add to it and maybe make it configurable.

**Comment by pferreir** [comment]
The ones I've blacklisted so far: JSON, YAML, Dockerfile, Pug, SCSS, CSS.

**Comment by sharedprophet** [comment]
Added JSON and Dockerfile to blacklist in 3.5.0. I like using CSS and LESS with semanticolor. With YAML you get good results if you set the "Source" setting to "mute". Haven't tried Pug or SCSS. Maybe those languages would work better with the addition of settings for scopes that aren't currently configurable? Use the "Log Cursor Scopes" command from the command palette to figure out if there's a scope that could be configured that would help you get the settings you want. If you find any, let me know here.

**Comment by peoro** [comment]
Pug (formerly Jade) is a markup language semantically similar to HTML. It's a real punch in the eye using atom with semanticolor on pug/jade files.

I currently disabled semanticolor just to be able to work with pug files, but would love any kind of other solution.

What are my other options?

**Comment by sharedprophet** [comment]
Just disable that syntax in the semanticolor settings.

**Comment by peoro** [comment]
Thanks, I managed to disable semanticolor.

I had to reload atom twice: once for semanticolor to list pug among the languages, and the second time to re-enable the default style after disabling semanticolor.

**Comment by RenaKunisaki** [comment]
After updating, I have the opposite problem - how do I make it the default? Every file I open, I have to manually select Semanticolor for the grammar.

**Comment by sharedprophet** [comment]
It should default to semanticolor for any grammar Semanticolor has enabled. After I updated I had to restart Atom before it behaved correctly. Let me know if that doesn't work.

**Comment by RenaKunisaki** [comment]
Yeah, I've restarted it twice now and it's not being used by default.

**Comment by sharedprophet** [comment]
> Yeah, I've restarted it twice now and it's not being used by default.

What language?

**Comment by RenaKunisaki** [comment]
Python and JavaScript.

**Comment by sharedprophet** [comment]
> Python and JavaScript.

Do you have Tree Sitter parsers enabled? (Settings -> Core -> Use Tree Sitter Parsers)

**Comment by RenaKunisaki** [comment]
That fixed it, thanks!
