### ISSUE TITLE
"Semanticolor settings have been changed!" dialog is annoying

### ISSUE THREAD

**Issue by pferreir** [xcezzz/semanticolor#21]
Especially because it shows up every single setting change that would trigger re-rendering (at least in my case). Would there be a way of making this operation explicit instead of forcing it on the user (or at least add an "I'll reload later" option)? Restarting the editor takes its time...

**Comment by sharedprophet** [comment]
I agree. I need to think more about if there's a way I could eliminate it entirely, but I could definitely add a "not now" option...

**Comment by sharedprophet** [comment]
Removed dialog. Semanticolor now updates settings without requiring Atom to be reloaded. Please get 3.5.0

**Comment by pferreir** [comment]
Sweet, thanks!
