### ISSUE TITLE
Global defaults for theme configuration

### ISSUE THREAD

**Issue by pferreir** [xcezzz/semanticolor#22]
*(Sorry, last one in my "issue spree")*

I don't like that default configuration disables keyword highlighting and set comments to 'contrast'. That's obviously a matter of personal preference, but I'd rather being able to set that for all languages in one go. Right now, I have to configure them one by one.
Maybe there could be a set global default settings and an additional (selected by default) 'inherit' option for each language setting?

*P.S.: I am more than willing to contribute a patch that implements this feature (same goes for #20 and #21), just let me know if you believe it's a good idea and, if it's ok for you, we can see how to best approach things.*

**Comment by sharedprophet** [comment]
Seems reasonable and pretty easy to implement. I'll work on it soon.

**Comment by sharedprophet** [comment]
Added global defaults in 3.5.0.
