### ISSUE TITLE
Colouring problems in Python

### ISSUE THREAD

**Issue by pferreir** [xcezzz/semanticolor#24]
See the way semanticolor handles `.format(...)` here:

![image](https://cloud.githubusercontent.com/assets/2699/26056242/ca16f4f2-3974-11e7-966a-8e88cc40e2ea.png)

I've seen this a few times in Python code. It looks like a bug to me. I used the "log cursor scope" feature and the `identifier.semanticolor-*` scope is indeed different. The other scopes are exactly the same.

**Comment by sharedprophet** [comment]
What other scopes are present for the f and the rest of the word? Aside from the semanticolor ones, is there a difference in the scope list?

**Comment by pferreir** [comment]
![image](https://cloud.githubusercontent.com/assets/2699/26065894/82fbe0a2-3995-11e7-89d5-6eaaad949813.png)
![image](https://cloud.githubusercontent.com/assets/2699/26065901/8c16e0b0-3995-11e7-8163-ad6d6a771569.png)

**Comment by sharedprophet** [comment]
Hmmmmm... I'll look into it. Thanks. : )

**Comment by pferreir** [comment]
If it helps, it only seems to happen when an attribute follows a parenthesized expression (e.g. `myfunc().myattribute`).

**Comment by sharedprophet** [comment]
So, it seems this is a bug in the Python language grammar for Atom. The `language-python-mamba` grammar doesn't have this issue. Basically, the grammar is identifying the first letter and the rest of the word as separate tokens, for some reason. I could maybe open a PR to fix the grammar...

**Comment by sharedprophet** [comment]
Looks like there is some work going on around replacing the crappy `language-python` module: https://github.com/atom/atom/pull/13877

**Comment by pferreir** [comment]
Thanks for having checked. I think I'll just used MagicPython for now, but good to know!
