### ISSUE TITLE
PHP keyword 'namespace' using scope 'name' setting instead of scope 'keyword'

### ISSUE THREAD

**Issue by mmn6d6d6e** [xcezzz/semanticolor#26]
![image](https://user-images.githubusercontent.com/19344000/29593927-78d86380-87d7-11e7-8bd1-a1bf35cda73a.png)

I'm using default semanticolor setting. Keyword 'namespace' should be muted instead of colorized.

Maybe because selector for scope 'name' select `syntax--*name*` or `syntax--name*`?

**Comment by sharedprophet** [comment]
What does it say when you put your cursor on the word 'namespace' and select Log Cursor Scopes from the command palette?

**Comment by mmn6d6d6e** [comment]
> Scopes at Cursor
> 
> - text.html.php
> - meta.embedded.block.php
> - source.php
> - meta.namespace.php
> - keyword.other.namespace.php
> - identifier.semanticolor-153

**Comment by sharedprophet** [comment]
Hmm, yes it is probably picking up name from the scope. Do you get good results if you set Names to 'defer'?

**Comment by mmn6d6d6e** [comment]
![image](https://user-images.githubusercontent.com/19344000/29599132-e6bd0bb0-87f7-11e7-9984-f825cb539fd3.png)

it's muted. yeah~ thx

**Comment by mmn6d6d6e** [comment]
But, yeah. Is keyword 'namespace' supposed to using setting from scope 'name' at all?

**Comment by sharedprophet** [comment]
Probably not. I will leave the issue open until I fix that.
