### ISSUE TITLE
Identifiers not colored consistenly.

### ISSUE THREAD

**Issue by ibbles** [xcezzz/semanticolor#3]
See screen capture below. For example, 'numTriangles' in function1 is one color in the function signature and another when used in the function. 

Have tried .c, .cpp, .glsl and .csh files and all have the same issue.

![semanticolor](https://cloud.githubusercontent.com/assets/8530401/9566905/f3e1716a-4f18-11e5-8600-4261b61a52f1.png)

**Comment by xcezzz** [comment]
Would it be possible to provide a developer tools 'inspection' of these variables?

META+ALT+I i think it is (on mac it is cmd+alt+i) to open the dev inspector

Then click the magnifying glass in the top left of the developer tools. Select one variable, screenshot the selected element and a bit of the surrounding elements... then do the same for the other variable that is colored differently and another screenshot including its element and a bit of the surrounding.

I have seen this occur sometimes when other modules end up altering the actual content of the tags, causing one to include the <comma><space> in the variable name leading it to calculate it as a different string.

**Comment by ibbles** [comment]
# From C source
## Signature
![semanticolor_c_signature](https://cloud.githubusercontent.com/assets/8530401/9704554/420d440c-54ac-11e5-9dae-4a81eb455df6.png)


## Usage
![semanticolor_c_inblock](https://cloud.githubusercontent.com/assets/8530401/9704556/4a709c20-54ac-11e5-85af-aa7f5cf79ebf.png)


# From GLSL source
## Signature
![semanticolor_glsl_signature](https://cloud.githubusercontent.com/assets/8530401/9704557/4eadb444-54ac-11e5-9921-3afa30a23e2e.png)

## Usage
![semanticolor_glsl_inblock](https://cloud.githubusercontent.com/assets/8530401/9704561/546d3710-54ac-11e5-91dc-465257ecf83c.png)

**Comment by ibbles** [comment]
You mentioned other plugins. For the screenshot below I renamed my .atom directory, installed semanticolor only and then re-took the C source signature screenshot.

![semanticolor_c_signature_nootherplugins](https://cloud.githubusercontent.com/assets/8530401/9704666/df25c1c2-54ae-11e5-8a14-48549277c4dd.png)

**Comment by xcezzz** [comment]
Interesting. I see. Well I guess it is not other plugins causing it. But apparently Atom is not consistently parsing the source. I had not tested this using the source languages you are using. Mainly JS, PHP, HTML,CSS and other scripted languages.

Will investigate a bit further on my end. Thank you.

**Comment by ferologics** [comment]
I'm using python and it doesn't work but I was looking for this for ages, please makes this happen. I have a lot of plugins by the way.. Not sure what's wrong

**Comment by mwchase** [comment]
I have a fresh install, plus semanticolor. In a simple python function, this happened:
![screen shot 2016-04-14 at 4 56 39 pm](https://cloud.githubusercontent.com/assets/882845/14543469/3f8f7f92-0262-11e6-800f-ef982d3a84ac.png)
The function is recursive, but at least all of the calls to the function are the same color, even if the definition is another one.

**Comment by xcezzz** [comment]
@mwchase Sorry... I gave up on Atom as an editor. It's tokenizer is absolutely garbage and cannot seem to properly tokenize things to make the semanticolor addon work properly.

I have reverted to sublime text as it is much more stable and provides a much more performant tokenizer and actually does it properly.

**Comment by ferologics** [comment]
Same.

On Mon, 25 Apr 2016 at 14:00 Chris <notifications@github.com> wrote:

> @mwchase <https://github.com/mwchase> Sorry... I gave up on Atom as an
> editor. It's tokenizer is absolutely garbage and cannot seem to properly
> tokenize things to make the semanticolor addon work properly.
>
> I have reverted to sublime text as it is much more stable and provides a
> much more performant tokenizer and actually does it properly.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/xcezzz/semanticolor/issues/3#issuecomment-214515033>
>
-- 
Frantisek Hetes, iOS Developer, Makeschool student
*f.hetes@gmail.com <f.hetes@gmail.com> | @ferbini | makeschool.com
<http://makeschool.com>*

**Comment by marnen** [comment]
@xcezzz I doubt that Atom's tokenizer is at fault here. The problem—at least for me—is that Semanticolor is treating, for example, `this` and `(this` as different identifiers (in JS), _even though_ Atom correctly tokenizes the `this` in both.

**Comment by alexrussell** [comment]
@xcezzz You should probably mark this package as abandoned in the README if you are no longer working on it.

**Comment by xcezzz** [comment]
@sharedprophet I have accepted a pull request from him that he said fixed and updated some of the issues. I do not have much time to test. Publishing his version now please confirm if resolved.

#6

**Comment by xcezzz** [comment]
I got a chance to quickly test in PHP, JS, CSS, HTML after #6 ... looks great! 

Published for updates on atom.io
