### ISSUE TITLE
Option to ignore specific grammars?

### ISSUE THREAD

**Issue by Lokidottir** [xcezzz/semanticolor#8]
There are cases where I need to outright ignore a grammar, as an example git diff using 3.0.0:

![semanticolor-git-diff](https://cloud.githubusercontent.com/assets/7648141/17170516/5971b8b6-53e4-11e6-8810-731c1e26af6d.png)

using settings:
```json
"semanticolor": {
		"colorOptions": {
			"fade": 40,
			"hues": 360,
			"luminosity": 50,
			"saturation": 90
		},
		"editorOptions": {
			"comment": "ignore",
			"constant_numeric": "ignore",
			"keyword": "colorize",
			"language": "ignore",
			"markup": "ignore",
			"operator": "ignore",
			"primitive": "colorize",
			"punctuation": "mute",
			"storage": "colorize",
			"string": "ignore",
			"support_constant": "colorize",
			"support_type": "colorize"
		}
}
```

***

Also, as someone with dyslexia who depends on this package a lot I'm happy to see it no longer being abandoned with the addition of a new maintainer.

**Comment by sharedprophet** [comment]
I'm going to make this happen in the next release, but in the meantime for any file that loads with Semanticolor that you want to see normally, you can click on the bottom right where it says Semanticolor - {grammar} and select the original grammar to disable coloring for that file.

**Comment by Lokidottir** [comment]
Lovely! Am looking forward.

**Comment by sharedprophet** [comment]
3.1.0 released on Saturday with this functionality.
